sudo: false
language: perl
perl:
   - '5.22'
   - '5.20'
   - '5.18'
   - '5.16'
   - '5.14'
   - '5.12'
   # Some deps are perl-5.012-and-above
   # and dzil does not work on blead for some reason.
   # - 'blead'
   # - '5.10'
   # - '5.8'
matrix:
   allow_failures:
      - perl: 'blead'
      - perl: '5.8'
   fast_finish: true
before_install:
   - git config --global user.name "TravisCI"
   - git config --global user.email $HOSTNAME":not-for-mail@travis-ci.org"
install:
   - cpanm --quiet --notest --skip-satisfied Dist::Zilla Pod::Weaver::Section::Support
   - "(cd Sky-uploader/App-Sky/ && dzil authordeps          --missing | grep -vP '[^\\w:]' | xargs -n 5 -P 10 cpanm --quiet --notest)"
   - "(cd Sky-uploader/App-Sky/ && dzil listdeps   --author --missing | grep -vP '[^\\w:]' | cpanm --verbose)"
script:
   - "cd Sky-uploader/App-Sky/ && dzil smoke --release --author"
